version: "2.1"

services:
    db:
        restart: always
        build: ./postgres
        image: youchendu/sieforum_db
        ports:
            - "5435:5432"
        networks:
            - blocked
            - default
    redis:
        restart: always
        build: ./redis
        image: youchendu/sieforum_redis
        networks:
            - blocked
    web:
        restart: always
        build: ./web
        image: youchendu/sieforum_web
        links:
            - db:db
            - redis:redis
        expose:
            - "8000"
        ports:
            - "8001:8001"
            - "8002:8002"
        depends_on:
            - db
            - redis
        volumes:
            - ./web/SIEForum:/SIEForum
            - /SIEForum/media
        networks:
            - default
            - blocked
    nginx:
        restart: always
        build: ./nginx
        image: youchendu/sieforum_nginx
        ports:
            - "9010:8000"
        links:
            - web:web
        volumes_from:
            - web
        networks:
            - default
    worker:
        restart: always
        build: ./worker
        image: youchendu/sieforum_worker
        volumes_from:
            - web:ro
        networks:
            - blocked

networks:
    blocked:
        internal: true
