# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0002_auto_20171023_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='status',
            field=models.IntegerField(choices=[(0, 'Solution pending'), (1, 'Solution running'), (2, 'Solution finished')], default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='submit_counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='solution',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='result',
            field=models.FloatField(default=-1),
        ),
    ]
