# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0004_solution_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='judge_name',
            field=models.CharField(default='default', max_length=40),
        ),
    ]
