# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0005_problem_judge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='module_name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
