# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0006_problem_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.IntegerField(choices=[(0, 'Solution pending'), (1, 'Solution running'), (2, 'Solution finished'), (-1, 'Solution error')], default=0),
        ),
    ]
