# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinejudge', '0007_auto_20171025_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='problem',
            name='order_type',
            field=models.CharField(choices=[('低值优先', 'Lower score first'), ('高值优先', 'Higher score first')], max_length=10),
        ),
        migrations.AddField(
            model_name='solutionranking',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinejudge.Problem'),
        ),
        migrations.AddField(
            model_name='solutionranking',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinejudge.Solution'),
        ),
        migrations.AddField(
            model_name='solutionranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
