# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0009_auto_20171028_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='submit_counter',
            field=models.IntegerField(default=0),
        ),
    ]
